In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

C:\Users\Shree\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
data = pd.read_csv("CSV 1.csv")

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 900 entries, 0 to 899
Data columns (total 26 columns):
id                       900 non-null int64
city                     900 non-null object
country                  900 non-null object
fullStreetAddress        900 non-null object
postalCode               900 non-null object
stateOrProvince          899 non-null object
unitNumber               118 non-null object
bathrooms                900 non-null int64
bedrooms                 900 non-null int64
listingDescription       842 non-null object
listingTitle             900 non-null object
latitude                 789 non-null float64
longitude                789 non-null float64
listPrice                900 non-null float64
livingArea               726 non-null float64
livingAreaUnit           900 non-null object
yearBuilt                791 non-null float64
lotSize                  562 non-null float64
lotSizeUnit              900 non-null object
propertySubType          900 non-null

In [4]:
data.describe()

id   bathrooms    bedrooms    latitude   longitude  \
count  9.000000e+02  900.000000  900.000000  789.000000  789.000000   
mean   1.379640e+06    2.220000    2.948889   36.058472  -88.433106   
std    8.350904e+05    1.359857    2.110319    5.520729   13.363031   
min    2.637000e+03    0.000000    0.000000   18.385107 -157.877612   
25%    6.939698e+05    1.000000    2.000000   32.650636  -94.836975   
50%    1.362506e+06    2.000000    3.000000   36.053461  -84.288388   
75%    2.034228e+06    3.000000    4.000000   40.744408  -80.175833   
max    2.698139e+06   13.000000   51.000000   48.093560  -66.163046   

          listPrice    livingArea    yearBuilt       lotSize  \
count  9.000000e+02    726.000000   791.000000  5.620000e+02   
mean   4.455732e+05   2084.289256  1979.609355  1.224170e+05   
std    4.869270e+06   4154.019862    44.355673  1.110570e+06   
min    2.850000e+02      0.000000  1111.000000  0.000000e+00   
25%    6.497500e+04   1233.000000  1962.000000  6.534000e+03   
50%    1.999000e+05   1684.000000  1987.000000  1.043262e+04   
75%    3.399250e+05   2289.500000  2005.000000  2.178000e+04   
max    1.450000e+08  99971.000000  2019.000000  1.899216e+07   

       numParkingSpaces  geocodioAccuracyScore  photoscount  
count        460.000000              27.000000   900.000000  
mean           3.919565               0.952963    18.700000  
std           46.660458               0.158012    16.242976  
min            0.000000               0.330000     0.000000  
25%            1.000000               1.000000     1.000000  
50%            2.000000               1.000000    19.000000  
75%            2.000000               1.000000    30.000000  
max         1002.000000               1.000000    91.000000

In [5]:
data.head()

id        city country          fullStreetAddress postalCode  \
0  2698139   St Peters      US     12 Legacy Estates Lane      63376   
1  2698093    St Louis      US          222 Euclid Avenue      63119   
2  2698007     Ballwin      US  741 Woodside Trails Drive      63021   
3  2697963  Manchester      US           301 Wembley Lane      63021   
4  2697938    O'fallon      US           27 Clear Meadows      63366   

  stateOrProvince unitNumber  bathrooms  bedrooms  \
0              MO        NaN          6         5   
1              MO        NaN          2         3   
2              MO        NaN          3         3   
3              MO        NaN          2         3   
4              MO        NaN          4         4   

                                  listingDescription  ... yearBuilt   lotSize  \
0  Tucked away in the private Legacy Estates subd...  ...    1998.0       NaN   
1  This charming Ranch offers hardwood flooring o...  ...    1962.0   7753.68   
2  This is the LARGEST Villa-style condo in this ...  ...    1986.0  14766.84   
3  Over 1700 sq ft of updated living space in con...  ...    1969.0  11848.32   
4  Move in ready, excellent condition. Outstandin...  ...    2007.0  10890.00   

   lotSizeUnit         propertySubType  listingCategory numParkingSpaces  \
0   squareFoot  Single Family Detached         Purchase              3.0   
1   squareFoot  Single Family Detached         Purchase              1.0   
2   squareFoot             Condominium         Purchase              2.0   
3   squareFoot  Single Family Detached         Purchase              2.0   
4   squareFoot  Single Family Detached         Purchase              3.0   

                    createdAt  geocodioAccuracyScore photoscount    grade  
0  2019-02-21 14:53:27.462+00                    NaN          29  awesome  
1   2019-02-21 14:53:07.92+00                    NaN          29  awesome  
2  2019-02-21 14:52:30.126+00                    NaN          29  awesome  
3   2019-02-21 14:52:11.85+00                    NaN          29  awesome  
4  2019-02-21 14:51:55.495+00                    NaN          29  awesome  

[5 rows x 26 columns]

In [6]:
# number of missing value in each cloumns
data.isnull().sum()

id                         0
city                       0
country                    0
fullStreetAddress          0
postalCode                 0
stateOrProvince            1
unitNumber               782
bathrooms                  0
bedrooms                   0
listingDescription        58
listingTitle               0
latitude                 111
longitude                111
listPrice                  0
livingArea               174
livingAreaUnit             0
yearBuilt                109
lotSize                  338
lotSizeUnit                0
propertySubType            0
listingCategory            0
numParkingSpaces         440
createdAt                  0
geocodioAccuracyScore    873
photoscount                0
grade                      0
dtype: int64

In [7]:
# drop the colums which have too much missing value like geocodioAccuracyScore

In [8]:
data = data.drop('geocodioAccuracyScore',1)

In [9]:
data = data.drop('unitNumber',1)

In [10]:
data = data.drop('listingDescription',1)

In [11]:
data.isnull().sum()

id                     0
city                   0
country                0
fullStreetAddress      0
postalCode             0
stateOrProvince        1
bathrooms              0
bedrooms               0
listingTitle           0
latitude             111
longitude            111
listPrice              0
livingArea           174
livingAreaUnit         0
yearBuilt            109
lotSize              338
lotSizeUnit            0
propertySubType        0
listingCategory        0
numParkingSpaces     440
createdAt              0
photoscount            0
grade                  0
dtype: int64

In [12]:
# filling the missing value 

In [13]:
data_mean=data['latitude'].mean()
data['latitude']=data['latitude'].fillna(data_mean)

In [14]:
data_mean=data['longitude'].mean()
data['longitude']=data['longitude'].fillna(data_mean)

In [15]:
data_mean=data['livingArea'].mean()
data['livingArea']=data['livingArea'].fillna(data_mean)

In [16]:
# fill by mode 
#data_mode=data['yearBuilt'].mode()
#data['yearBuilt']=data['yearBuilt'].fillna(data_mode)

In [17]:
data_mean=data['lotSize'].mean()
data['lotSize']=data['lotSize'].fillna(data_mean)

In [18]:
data_mean=data['numParkingSpaces'].mean()
data['numParkingSpaces']=data['numParkingSpaces'].fillna(data_mean)

In [19]:
# fill missing value with highest_frequency

In [20]:
print(data.groupby('yearBuilt').size())

yearBuilt
1111.0     1
1800.0     1
1820.0     1
1850.0     1
1860.0     1
1875.0     1
1876.0     1
1881.0     1
1886.0     1
1889.0     1
1890.0     3
1892.0     1
1893.0     1
1899.0     2
1900.0     7
1901.0     1
1903.0     1
1904.0     1
1906.0     1
1907.0     2
1908.0     1
1910.0     3
1920.0     9
1922.0     3
1923.0     5
1924.0     1
1925.0     3
1926.0     3
1927.0     2
1928.0     2
          ..
1990.0     5
1991.0     5
1992.0     7
1993.0    10
1994.0     8
1995.0    18
1996.0     6
1997.0     5
1998.0    10
1999.0    15
2000.0    14
2001.0     4
2002.0    13
2003.0    20
2004.0    23
2005.0    18
2006.0    24
2007.0    18
2008.0    15
2009.0     6
2010.0     5
2011.0     4
2012.0     5
2013.0     5
2014.0    10
2015.0     6
2016.0     6
2017.0    15
2018.0    55
2019.0     9
Length: 116, dtype: int64


In [21]:
year_b=2019

In [22]:
data['yearBuilt']=data['yearBuilt'].fillna(year_b)

In [23]:
print(data.groupby('stateOrProvince').size())

stateOrProvince
AL     18
AR     15
AZ     32
CA     34
CO      3
CT      2
DC      2
DE      1
FL    166
GA     43
HI      1
IA     18
ID      6
IL     26
IN     10
KS     10
KY     15
LA     14
MA      4
MD      8
ME      9
MI     22
MN      4
MO     29
MS      3
MT      1
NC     29
NE      9
NH      2
NJ     36
NM      6
NV     53
NY     64
OH     11
OK     14
ON      2
OR      7
PA     12
PR      2
RI      3
SC     18
SD      1
TN     24
TX     51
UT      3
VA     23
VT      2
WA      9
WI     16
WV      3
WY      3
dtype: int64


In [24]:
#print(data.groupby('listingDescription').size())

In [25]:
data_s=('FL')

In [26]:
data['stateOrProvince']=data['stateOrProvince'].fillna(data_s)

In [27]:
data.isnull().sum()

id                   0
city                 0
country              0
fullStreetAddress    0
postalCode           0
stateOrProvince      0
bathrooms            0
bedrooms             0
listingTitle         0
latitude             0
longitude            0
listPrice            0
livingArea           0
livingAreaUnit       0
yearBuilt            0
lotSize              0
lotSizeUnit          0
propertySubType      0
listingCategory      0
numParkingSpaces     0
createdAt            0
photoscount          0
grade                0
dtype: int64

In [28]:
#  assume  grade as target variable 

In [29]:
y = data.grade

In [30]:
y.head()

0    awesome
1    awesome
2    awesome
3    awesome
4    awesome
Name: grade, dtype: object

In [31]:
y=pd.get_dummies(y)

In [32]:
y.head(5)

awesome  bad  good
0        1    0     0
1        1    0     0
2        1    0     0
3        1    0     0
4        1    0     0

In [33]:
print(data.groupby('grade').size())

grade
awesome    300
bad        299
good       301
dtype: int64


In [34]:
data =data.drop('grade',axis=1)

In [35]:
# we drop some string data type variable because string data type need some data preprocessing for better result 

In [36]:
data = data.drop('createdAt',axis=1)

In [37]:
data = data.drop('listingTitle',axis=1)

In [38]:
data = data.drop('fullStreetAddress',axis=1)

In [39]:
data.head()

id        city country postalCode stateOrProvince  bathrooms  \
0  2698139   St Peters      US      63376              MO          6   
1  2698093    St Louis      US      63119              MO          2   
2  2698007     Ballwin      US      63021              MO          3   
3  2697963  Manchester      US      63021              MO          2   
4  2697938    O'fallon      US      63366              MO          4   

   bedrooms   latitude  longitude  listPrice  livingArea livingAreaUnit  \
0         5  36.058472 -88.433106   425000.0      3046.0     squareFoot   
1         3  36.058472 -88.433106   175000.0      1587.0     squareFoot   
2         3  36.058472 -88.433106   295000.0      2437.0     squareFoot   
3         3  36.058472 -88.433106   215000.0      1780.0     squareFoot   
4         4  36.058472 -88.433106   375000.0      3405.0     squareFoot   

   yearBuilt        lotSize lotSizeUnit         propertySubType  \
0     1998.0  122417.000783  squareFoot  Single Family Detached   
1     1962.0    7753.680000  squareFoot  Single Family Detached   
2     1986.0   14766.840000  squareFoot             Condominium   
3     1969.0   11848.320000  squareFoot  Single Family Detached   
4     2007.0   10890.000000  squareFoot  Single Family Detached   

  listingCategory  numParkingSpaces  photoscount  
0        Purchase               3.0           29  
1        Purchase               1.0           29  
2        Purchase               2.0           29  
3        Purchase               2.0           29  
4        Purchase               3.0           29

In [40]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 900 entries, 0 to 899
Data columns (total 19 columns):
id                  900 non-null int64
city                900 non-null object
country             900 non-null object
postalCode          900 non-null object
stateOrProvince     900 non-null object
bathrooms           900 non-null int64
bedrooms            900 non-null int64
latitude            900 non-null float64
longitude           900 non-null float64
listPrice           900 non-null float64
livingArea          900 non-null float64
livingAreaUnit      900 non-null object
yearBuilt           900 non-null float64
lotSize             900 non-null float64
lotSizeUnit         900 non-null object
propertySubType     900 non-null object
listingCategory     900 non-null object
numParkingSpaces    900 non-null float64
photoscount         900 non-null int64
dtypes: float64(7), int64(4), object(8)
memory usage: 133.7+ KB


In [41]:
# One_Hot encoding 

In [42]:
cat = data.select_dtypes(include=['object']).columns
name=[]
for i in cat:
    name.append(i)

In [43]:
non_cat=data.drop(name,axis=1)
cat=data.drop(non_cat,axis=1)

In [44]:
cat.head()

city country postalCode stateOrProvince livingAreaUnit lotSizeUnit  \
0   St Peters      US      63376              MO     squareFoot  squareFoot   
1    St Louis      US      63119              MO     squareFoot  squareFoot   
2     Ballwin      US      63021              MO     squareFoot  squareFoot   
3  Manchester      US      63021              MO     squareFoot  squareFoot   
4    O'fallon      US      63366              MO     squareFoot  squareFoot   

          propertySubType listingCategory  
0  Single Family Detached        Purchase  
1  Single Family Detached        Purchase  
2             Condominium        Purchase  
3  Single Family Detached        Purchase  
4  Single Family Detached        Purchase

In [45]:
dummy=pd.get_dummies(cat,drop_first=True)

In [46]:
dummy.head()

city_Abbeville  city_Acworth  city_Aiken  city_Akron  city_Albany  \
0               0             0           0           0            0   
1               0             0           0           0            0   
2               0             0           0           0            0   
3               0             0           0           0            0   
4               0             0           0           0            0   

   city_Albuquerque  city_Allen  city_Allentown  city_Alta  city_Altoona  ...  \
0                 0           0               0          0             0  ...   
1                 0           0               0          0             0  ...   
2                 0           0               0          0             0  ...   
3                 0           0               0          0             0  ...   
4                 0           0               0          0             0  ...   

   propertySubType_Mobile Home  propertySubType_Other  \
0                            0                      0   
1                            0                      0   
2                            0                      0   
3                            0                      0   
4                            0                      0   

   propertySubType_Quadruplex  propertySubType_Single Family Attached  \
0                           0                                       0   
1                           0                                       0   
2                           0                                       0   
3                           0                                       0   
4                           0                                       0   

   propertySubType_Single Family Detached  propertySubType_Stock Cooperative  \
0                                       1                                  0   
1                                       1                                  0   
2                                       0                                  0   
3                                       1                                  0   
4                                       1                                  0   

   propertySubType_Timeshare  propertySubType_Townhouse  \
0                          0                          0   
1                          0                          0   
2                          0                          0   
3                          0                          0   
4                          0                          0   

   propertySubType_Triplex  listingCategory_Rent  
0                        0                     0  
1                        0                     0  
2                        0                     0  
3                        0                     0  
4                        0                     0  

[5 rows x 1462 columns]

In [47]:
frame=[dummy,non_cat]

In [48]:
data=pd.concat(frame,axis=1)

In [49]:
data.head()

city_Abbeville  city_Acworth  city_Aiken  city_Akron  city_Albany  \
0               0             0           0           0            0   
1               0             0           0           0            0   
2               0             0           0           0            0   
3               0             0           0           0            0   
4               0             0           0           0            0   

   city_Albuquerque  city_Allen  city_Allentown  city_Alta  city_Altoona  ...  \
0                 0           0               0          0             0  ...   
1                 0           0               0          0             0  ...   
2                 0           0               0          0             0  ...   
3                 0           0               0          0             0  ...   
4                 0           0               0          0             0  ...   

   bathrooms  bedrooms   latitude  longitude  listPrice  livingArea  \
0          6         5  36.058472 -88.433106   425000.0      3046.0   
1          2         3  36.058472 -88.433106   175000.0      1587.0   
2          3         3  36.058472 -88.433106   295000.0      2437.0   
3          2         3  36.058472 -88.433106   215000.0      1780.0   
4          4         4  36.058472 -88.433106   375000.0      3405.0   

   yearBuilt        lotSize  numParkingSpaces  photoscount  
0     1998.0  122417.000783               3.0           29  
1     1962.0    7753.680000               1.0           29  
2     1986.0   14766.840000               2.0           29  
3     1969.0   11848.320000               2.0           29  
4     2007.0   10890.000000               3.0           29  

[5 rows x 1473 columns]

In [50]:
from sklearn.model_selection import train_test_split

In [51]:
X_train,X_test,y_train,y_test = train_test_split(data,y,test_size=0.30, random_state=42)

In [52]:
from sklearn.ensemble import RandomForestClassifier
rnd=RandomForestClassifier(n_estimators=100)

In [53]:
rnd.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [54]:
rnd.score(X_train,y_train)

1.0

In [55]:
rnd.score(X_test,y_test)

0.9037037037037037

In [56]:
rnd_predict = rnd.predict(X_test) 

In [57]:
print(rnd_predict)

[[1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1.

In [58]:
from sklearn import tree

In [59]:
clf = tree.DecisionTreeClassifier()

In [60]:
clf.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [61]:
clf.score(X_train,y_train)

1.0

In [62]:
clf.score(X_test,y_test)

0.9407407407407408

In [63]:
# classify  using the  ANN 
# our data set is small in  size ,

In [64]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

C:\Users\Shree\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\Shree\Anaconda3\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
C:\Users\Shree\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by StandardScaler.
  after removing the cwd from sys.path.


In [65]:
import keras

Using TensorFlow backend.


In [66]:
from keras.models import Sequential

In [67]:
from keras.layers import Dense, Activation

In [68]:
classifier = Sequential()

In [69]:
classifier.add(Dense(output_dim = 360, init = 'uniform', activation = 'relu', input_dim = 1473))

Instructions for updating:
Colocations handled automatically by placer.


C:\Users\Shree\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=1473, units=360, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [70]:
classifier.add(Dense(output_dim = 36, init = 'uniform', activation = 'relu'))

C:\Users\Shree\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=36, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [71]:
classifier.add(Dense(output_dim = 3, init = 'uniform', activation = 'softmax'))

C:\Users\Shree\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="softmax", units=3, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [72]:
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [ ]:
classifier.fit(X_train, y_train, nb_epoch = 100)

Epoch 1/100
224/630 [=========>....................] - ETA: 0s - loss: 0.0116 - acc: 0.9940

C:\Users\Shree\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


630/630 [==============================] - 0s 616us/step - loss: 0.0113 - acc: 0.9947
Epoch 2/100
630/630 [==============================] - 0s 650us/step - loss: 0.0062 - acc: 0.9958
Epoch 3/100
630/630 [==============================] - 0s 665us/step - loss: 0.0054 - acc: 0.9968
Epoch 4/100
630/630 [==============================] - 0s 676us/step - loss: 0.0047 - acc: 0.9989
Epoch 5/100
630/630 [==============================] - 0s 665us/step - loss: 0.0039 - acc: 0.9989
Epoch 6/100
630/630 [==============================] - 0s 684us/step - loss: 0.0044 - acc: 0.9979
Epoch 7/100
630/630 [==============================] - 0s 681us/step - loss: 0.0042 - acc: 0.9989
Epoch 8/100
630/630 [==============================] - 0s 671us/step - loss: 0.0031 - acc: 0.9989
Epoch 9/100
630/630 [==============================] - 0s 668us/step - loss: 0.0030 - acc: 0.9989
Epoch 10/100
630/630 [==============================] - 0s 668us/step - loss: 0.0024 - acc: 1.0000
Epoch 11/100
630/630 [=========

630/630 [==============================] - 0s 630us/step - loss: 2.7158e-04 - acc: 1.0000
Epoch 82/100
630/630 [==============================] - 0s 708us/step - loss: 2.4575e-04 - acc: 1.0000
Epoch 83/100
630/630 [==============================] - 0s 655us/step - loss: 2.1742e-04 - acc: 1.0000
Epoch 84/100
448/630 [====================>.........] - ETA: 0s - loss: 3.2507e-04 - acc: 1.0000

In [ ]:
score = classifier.evaluate(X_test, y_test)

In [ ]:
classifier.metrics_names

In [ ]:
score

In [77]:
# our Ann model is overfit due to small  dataset